---
- hosts: all
  become: yes
  tasks:
     - name: "apt-get update"
       apt:
         update_cache: yes
         cache_valid_time: 3600

     - name: Install prerequisites
       apt: 
        name: [ 'aptitude' ]
        state: latest  

     - name: "Instalacion de nginx php y mysql"
       apt:
         name: [ 'nginx', 'apache2', 'mysql-server', 'python3-pymysql', 'php-fpm', 'php-mysql']
         state: latest

     - name: Sets Nginx conf file
       template:
         src: templates/site.conf.j2
         dest: /etc/nginx/sites-available/www.lgarnica.com

     - name: "create www dictory"
       file:
         path: /var/www/{{ domain }}
         state: directory
         mode: '0755'
         owner: "{{ ansible_user }}"
         group: "{{ ansible_user }}"

     - name: pasar pagina web
       git:
         repo: https://github.com/LFluna/PaginaWEB.git
         dest: /var/www/{{ domain }}

     - name: copy nginx site.conf
       template:
          src: site.conf.j2
          dest: /etc/nginx/sites-enabled/{{ domain }}
          owner: root
          group: root
          mode: '0644'
       notify: reload nginx



  
     - name: configurar firewall
       ufw:
        rule: allow
        port: "80"
        proto: tcp


  handlers:
     - name: reload nginx
       service:
         name: nginx
         state: reloaded

     - name: restart nginx
       service:
         name: nginx
         state: restarted
      
